feat(deployment): separate build and deployment into distinct jobs

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,4 +1,4 @@
-name: Build and publish Docker container
+name: Build and deploy Docker container
 
 on:
   push:
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  docker:
+  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -40,6 +40,17 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
       - name: Trigger container update
         run: |
-          curl  -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" https://watchtower.aid-ly.org
+          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" https://watchtower.aid-ly.org)
+          if [ "$response" -eq 200 ]; then
+            echo "Deployment triggered successfully: Watchtower API responded with status $response."
+            exit 0
+          fi
+
+          echo "Failed to trigger deployment: Watchtower API responded with status $response."
+          exit 1
